// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once

#include "frc2/command/PIDSubsystem.h"
#include "frc/controller/PIDController.h"

#include "rev/CANSparkMax.h"
#include "frc/Encoder.h"
#include "frc/SpeedControllerGroup.h"

class DrivePID: public frc2::PIDSubsystem {

	rev::CANSparkMax *left1;
	rev::CANSparkMax *left2;
	rev::CANSparkMax *left3;
	frc::SpeedControllerGroup *leftSide;
	rev::CANSparkMax *right1;
	rev::CANSparkMax *right2;
	rev::CANSparkMax *right3;
	frc::SpeedControllerGroup *rightSide;

 	frc2::PIDController& pidController;
public:
	DrivePID();
	double GetMeasurement() override;
	void UseOutput(double output, double setpoint) override;
};

