// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc2/command/Subsystem.h"
#include "rev/CANSparkMax.h"
#include "ctre/Phoenix.h"
#include "frc/DigitalInput.h"
#include "frc/PowerDistributionPanel.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Feeder: public frc2::Subsystem {
  private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	frc::PowerDistributionPanel *pDBoard;
	frc::DigitalInput *photoEye;

	rev::CANSparkMax *hopperLeft;
	rev::CANSparkMax *hopperRight;
	rev::CANSparkMax *intake;

  public:
	Feeder();


};

