// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once

#include "frc2/command/PIDSubsystem.h"
#include "frc/controller/PIDController.h"
#include "rev/CANSparkMax.h"
#include "ctre/Phoenix.h"
#include "frc/Encoder.h"
#include "frc/SpeedControllerGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ShooterPID: public frc2::PIDSubsystem {
	//TalonFX is the Falcon motor controller
	ctre::phoenix::motorcontrol::can::WPI_TalonFX *shooter1;
	ctre::phoenix::motorcontrol::can::WPI_TalonFX *shooter2;
	frc::SpeedControllerGroup *shooterGroup;
	frc2::PIDController& pidController;

    rev::CANSparkMax *tower1;
	rev::CANSparkMax *tower2;
	frc::SpeedControllerGroup *towerGroup;
 public:
	ShooterPID();
	double GetMeasurement() override;
	void UseOutput(double output, double setpoint) override;
	
	void SetShooterSpeed(double rpm);
};

