// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// See this link fo rmore info about simplified commands
// https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html


#include "Commands/ArcadeDriveCommand.h"
#include "Robot.h"







ArcadeDriveCommand::ArcadeDriveCommand(double speed, double rotation, double length) {
  m_speed = speed;
  m_rotation = rotation;
  m_time = (units::second_t)length;
}

// Called when the command is initially scheduled.
void ArcadeDriveCommand::Initialize() {
  Robot::drivePID.get()->ArcadeDrive(m_speed, m_rotation);
  m_timer.Reset();
  m_timer.Start();
}

void ArcadeDriveCommand::Execute() {
Robot::drivePID.get()->ArcadeDrive(-0.25, 0);
}

void ArcadeDriveCommand::End(bool interrupted) {
  m_timer.Stop();
  Robot::drivePID.get()->ArcadeDrive(0, 0);
}

// Return true right away because the we only need to set the shooter speed once.
bool ArcadeDriveCommand::IsFinished() {
 if (m_timer.Get() >= m_time) {
    return true;
  }
  else {
    return false;
  }
}
