// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// See this link fo rmore info about simplified commands
// https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html


#include "Robot.h"
#include "Commands/RaiseTower.h"

RaiseTower::RaiseTower(double speed) {
  m_speed = speed;
}

// Called repeatedly when this Command is scheduled to run
void RaiseTower::Initialize() {
  Robot::shooterPID.get()->SetTowerSpeed(m_speed);
}

bool RaiseTower::IsFinished() {
  return true;
}
