// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// See this link fo rmore info about simplified commands
// https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html


#include "Commands/SetShooterSpeedCommand.h"
#include "Robot.h"

SetShooterSpeedCommand::SetShooterSpeedCommand(double rpm) {
  // AddRequirements(Robot::shooterPID.get());
  m_shooterSpeed = rpm;
}

// Called when the command is initially scheduled.
void SetShooterSpeedCommand::Initialize() {
   Robot::shooterPlain.get()->setRpm(m_shooterSpeed);
}

// Called when the command is initially scheduled.
void SetShooterSpeedCommand::Execute() {
   Robot::shooterPlain.get()->setRpm(m_shooterSpeed);
}

// Return true right away because the we only need to set the shooter speed once.
bool SetShooterSpeedCommand::IsFinished() { 
  //std::cout << "Shooter is Finished!" << std::endl;
  return false; 
}

void SetShooterSpeedCommand::End(bool interrupted)
{
   Robot::shooterPlain.get()->setRpm(500);
}