// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// See this link fo rmore info about simplified commands
// https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html


#include"Robot.h"
#include "Commands/SetTargetTracking.h"

SetTargetTracking::SetTargetTracking(bool track) {
  m_enableTracking = track;
}

// Called when the command is initially scheduled.
void SetTargetTracking::Initialize() {
  Robot::turret.get()->SetTracking(m_enableTracking);
}

// Returns true when the command should end.
bool SetTargetTracking::IsFinished() { return true; }
