// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// See this link fo rmore info about simplified commands
// https://docs.wpilib.org/en/latest/docs/software/commandbased/convenience-features.html


#include "Robot.h"
#include "Commands/WaveWaitCommand.h"

WaveWaitCommand::WaveWaitCommand(double length) {
  m_time = (units::second_t)length;
}

// Called repeatedly when this Command is scheduled to run
void WaveWaitCommand::Initialize() {
  m_timer.Reset();
  m_timer.Start();
}

void WaveWaitCommand::Execute() {
  //std::cout << "Time: " << m_timer.Get() << ", m_time " << m_time << std::endl;
}

void WaveWaitCommand::End(bool interrupted) {
  m_timer.Stop();
}

bool WaveWaitCommand::IsFinished() {
  if (m_timer.Get() >= m_time) {
    return true;
  }
  else {
    return false;
  }
}