// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Feeder.h"
#include "Reference.h"


Feeder::Feeder() : frc::Subsystem("Feeder") {

    feederMotor.reset(new WPI_TalonSRX(FEEDER));


    pDBoard.reset(new frc::PowerDistributionPanel(0));
    //AddChild("PDBoard", pDBoard);

    photoEye.reset(new frc::DigitalInput(6));
    //AddChild("PhotoEye", photoEye);

}

void Feeder::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());

}

void Feeder::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

